"""Initial migration with User and Student models

Revision ID: 1ef8749eb33e
Revises: 
Create Date: 2025-11-18 22:40:01.584086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef8749eb33e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False, comment='学号'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment="年级，如 '2023级'") ,
    sa.Column('major', sa.String(length=100), nullable=True, comment='专业'),
    sa.Column('class_name', sa.String(length=50), nullable=True, comment='班级'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='最后更新人'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态（如：active, inactive, pending 等）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号，值越小越靠前'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息，可用于记录额外说明'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    
    # 创建users表
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0'), comment='软删除标志'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='最后更新人'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态（如：active, inactive, pending 等）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='排序序号，值越小越靠前'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息，可用于记录额外说明'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
